Refactoring firstboot.d/01ipconfig

diff --git a/firstboot.d/01ipconfig b/firstboot.d/01ipconfig
--- a/firstboot.d/01ipconfig
+++ b/firstboot.d/01ipconfig
@@ -3,62 +3,48 @@
 
 . /etc/default/inithooks
 
-[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
-[ -z "$IP_CONFIG" ] && exit 0
-[ "$IP_CONFIG" != "manual" ] && [ "$IP_CONFIG" != "static" ] && [ "$IP_CONFIG" != "dhcp" ] && exit 1
-[ ! -e /etc/network/interfaces ] && exit 1
+fatal() { echo "fatal $@" >&2; exit 1; }
 
-APP=$(turnkey-version | sed 's/turnkey-\(.*\)-[0-9]\+\.[0-9]\+-.*$/\1/')
+[[ -e $INITHOOKS_CONF ]] && . $INITHOOKS_CONF
+[[ -z "$IP_CONFIG" ]] && exit 0
+[[ "$IP_CONFIG" != "manual" ]] \
+    && [[ "$IP_CONFIG" != "static" ]] \
+    && [[ "$IP_CONFIG" != "dhcp" ]] \
+    && fatal "IP_CONFIG set incorrectly"
+[[ ! -e /etc/network/interfaces ]] && fatal "intefaces file not found"
+
+APP=$(turnkey-version -n)
 
 IP_IFACE="eth0"
-[ "$APP" == "lxc" ] && IP_IFACE="br0"
+[[ "$APP" == "lxc" ]] && IP_IFACE="br0"
 
-# if IP_CONFIG is not changed skip this script and avoid a interface reconfiguration
-grep "iface $IP_IFACE inet $IP_CONFIG" /etc/network/interfaces >/dev/null && exit 0
+# if IP_CONFIG is not changed skip this script and avoid a interface
+# reconfiguration
+grep "iface $IP_IFACE inet $IP_CONFIG" /etc/network/interfaces >/dev/null \
+    && exit 0
 
-ifdown --exclude=lo -a
-
-# since debian 8 (systemd) ifdown does no longer take the interface down
-# if we change between manual, static or dhcp this does not work anymore
-# as ifup won't do anything
+# since debian 8 (systemd) ifdown no longer takes the interface down if we
+change between manual, static or dhcp so using 'ip' instead
 ip link set $IP_IFACE down
 
-# remove modified or unecessary options, regardless of order
-  sed -i "/auto $IP_IFACE/,/^$/ {
-  /hostname/ d
-  /address/ d
-  /netmask/ d
-  /gateway/ d
-  /dns-nameservers/ d
-  }" /etc/network/interfaces
+cat > /etc/network/interfaces <<EOF
+# interfaces(5) file - generated by TurnKey firstboot
 
-# configure 'manual' interface
-if [ "$IP_CONFIG" = "manual" ]; then
-  sed -i "/auto $IP_IFACE/,/^$/ {
-  /iface/ s/[^ ]*$/manual/
-  }" /etc/network/interfaces
-fi
+auto lo
+iface lo inet loopback
 
-# configure 'dhcp' interface
-if [ "$IP_CONFIG" = "dhcp" ]; then
-  sed -i "/auto $IP_IFACE/,/^$/ {
-  /iface/ s/[^ ]*$/dhcp/
-  /iface/ a\\
-    hostname $HOSTNAME
-  }" /etc/network/interfaces
-fi
+auto $IP_IFACE
+iface $IP_IFACE inet $IP_CONFIG
+    hostname $(head -1 /etc/hostname)
+EOF
 
-# configure 'static' interface
-if [ "$IP_CONFIG" = "static" ]; then
-  sed -i "/auto $IP_IFACE/,/^$/ {
-  /iface/ s/[^ ]*$/static/
-  /iface/ a\\
-    address $IP_ADDRESS\\
-    netmask $IP_NETMASK\\
-    gateway $IP_GW\\
+if [[ "$IP_CONFIG" == "static" ]]; then
+    cat > /etc/network/interfaces <<EOF
+    address $IP_ADDRESS
+    netmask $IP_NETMASK
+    gateway $IP_GW
     dns-nameservers $IP_DNS1 $IP_DNS2
-  }" /etc/network/interfaces
-fi
+EOF
 
 ifup --exclude=lo -a
 
