Remove 15regen-dhparams and rely on new dhparam functionality of turnkey-make-ssl-cert - part of #1432.

diff --git a/firstboot.d/15regen-sslcert b/firstboot.d/15regen-sslcert
--- a/firstboot.d/15regen-sslcert
+++ b/firstboot.d/15regen-sslcert
@@ -1,20 +1,22 @@
 #!/bin/bash -e
-# Regenerate self-signed TLS (aka SSL) keys and certificates
+# Regenerate self-signed TLS/SSL cert, key & dhparams
 
 [ -n "$_TURNKEY_INIT" ] && exit 0
 
-# dhparams generation moved to separate firstboot script
+# Support preseeding of DH_BITS
+[[ -e $INITHOOKS_CONF ]] && . $INITHOOKS_CONF
 
-echo "Regenerating self-signed TLS (aka SSL) keys and certificates..."
+fatal() { echo "fatal: $@" 1>&2 ; exit 1 }
 
-# Use turnkey-make-ssl-cert to generate default server cert
-# This script should be provided by common/overlays/turnkey.d/sslcert
-if which turnkey-make-ssl-cert >/dev/null; then
-    /usr/local/bin/turnkey-make-ssl-cert --default --force-overwrite
-else
-    echo "fatal: turnkey-make-ssl-cert not found"
-    exit 1
-fi
+turnkey_make_ssl_cert=$(which turnkey-make-ssl-cert) \
+    || fatal "turnkey-make-ssl-cert executable not found."
+
+DH_BITS=${DH_BITS:-1024}
+# This script should be provided by common/overlays/turnkey.d/sslcert.
+# As of v16.0 will also generate a default dhparams file (1024 bits)
+echo "Generating SSL/TLS cert, key & default ($DH_BITS bit) dhparams file."
+echo "Note: a dhparams file of bit size >= 2048 is recommended."
+$turnkey_make_ssl_cert --default --force-overwrite --dh-bits $DH_BITS
 
 # Restart relevant services
 SERVICENAMES="\
@@ -25,7 +27,7 @@ SERVICENAMES="\
     stunnel4@webmin
     stunnel4@shellinabox"
 
-echo "(re)starting relevant services"
+echo "Restarting relevant services."
 for servicename in $SERVICENAMES; do
     if systemctl list-units --full -all | grep -Fq $servicename.service; then
         echo "$servicename.service found; (re)starting..."
