Resolved merge conflict between xen and lxc v15.0 updates

diff --git a/run b/run
--- a/run
+++ b/run
@@ -4,11 +4,23 @@
 INITHOOKS_DEFAULT=/etc/default/inithooks
 . $INITHOOKS_DEFAULT
 
+TKLINFO=/var/lib/turnkey-info/inithooks.service
+
 if [ "$(echo $REDIRECT_OUTPUT | tr [A-Z] [a-z] )" = "true" ]; then
     # redirect stdout/stderr (use when preseeding headless deployments)
     LOGFILE=/var/log/inithooks.log
     touch $LOGFILE; chmod 640 $LOGFILE
-    echo "Redirecting output to $LOGFILE"
+
+    # on xen redirection is performed by the inithooks-xen service
+    # on lxc redirection is handled below
+    # otherwise redirection is handled by inithooks service and redirected to tty8
+
+    if [ -f "$TKLINFO/lxc" ]; then
+        TTY=$(cat /sys/devices/virtual/tty/tty0/active)
+        [ -z $TTY ] && TTY=console
+        tail -f $LOGFILE > /dev/$TTY &
+        PID="$!"
+    fi
 fi
 
 exec_scripts() {
@@ -17,8 +29,9 @@ exec_scripts() {
     for SCRIPT in $(find $SCRIPT_DIR -type f -or -type l | sort); do
         [ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
         [ -x $SCRIPT ] || continue
-        echo "# $SCRIPT"
+        echo "# running $SCRIPT"
         $SCRIPT
+        echo "# completed $SCRIPT - exit code $?"
     done
     return 0
 }
@@ -30,5 +43,9 @@ if [ "$(echo $RUN_FIRSTBOOT | tr [A-Z] [a-z] )" = "true" ]; then
     exec_scripts $INITHOOKS_PATH/firstboot.d
 fi
 exec_scripts $INITHOOKS_PATH/everyboot.d
+
+if [ -n "$PID" ];  then
+    kill -9 $PID || true
+fi
 
 exit 0
